# action.yml
name: 'Create vpn'
description: 'Trigger vpn'
inputs:
  docker-port-1:
    description: 'docker port 1'
    required: true    
  docker-port-2:
    description: 'docker port 2'
    required: true        
docker-port-3:
    description: 'docker port 3'
    required: true            
  vpn-ip:
    description: 'vpn ip address'
    required: true
  vpn-port:
    description: 'vpn port'
    required: true    
  vpn-user:
    description: 'vpn user'
    required: true    
  vpn-password:
    description: 'vpn password'
    required: true
  vpn-token:
    description: ""
    required: true
  proxy-ip:
    description: 'proxy ip address'
    required: true
  proxy-prot:
    description: 'proxy port'
    required: true    
  proxy-user:
    description: 'proxy user'
    required: true
  proxy-password:
    description: "proxy password"
    required: true
  jump-ip:
    description: 'jump server ip'
    required: true
  jump-port:
    description: 'jump server port'
    required: true    
  jump-user:
    description: 'jump server user'
    required: true
  jump-password:
    description: 'jump server password'
    required: true
  target-ip-1:
    description: 'target server ip 1'
    required: true
  target-port-1:
    description: 'target server port 1'
    required: true    
  target-ip-2:
    description: 'target server ip 2'
    required: true
  target-port-2:
    description: 'target server port 2'
    required: true        
  target-ip-3:
    description: 'target server ip 3'
    required: true
  target-port-3:
    description: 'target server port 3'
    required: true     
    
outputs:
  job_status:
    description: 'VPN  status'
runs:
  using: 'docker'
  image: 'docker://yintro4ha/yintro-github-action-vpn:v1'
  env:
    DOCKER_PORT_1: ${{ inputs.docker-port-1}}
    DOCKER_PORT_2: ${{ inputs.docker-port-2}}
    DOCKER_PORT_3: ${{ inputs.docker-port-3}}
    VPN_IP: ${{ inputs.vpn-ip}}
    VPN_PORT: ${{ inputs.vpn-port}}
    VPN_USER: ${{ inputs.vpn-user}}
    VPN_PASSWORD: ${{ inputs.vpn-password}}
    VPN_TOKEN: ${{ inputs.vpn-token}}
    PROXY_IP: ${{ inputs.proxy-ip}}
    PROXY_PORT: ${{ inputs.proxy-prot}}
    POXY_USER: ${{ inputs.proxy-user}}
    PROXY_PASSWORD: ${{ inputs.proxy-password}}
    JUMP_IP: ${{ inputs.jump-ip}}
    JUMP_PORT: ${{ inputs.jump-port}}
    JUMP_USER: ${{ inputs.jump-user}}
    JUMP_PASSWORD: ${{ inputs.jump-password}}
    TARGET_IP_1: ${{ inputs.target-ip-1}}
    TARGET_PORT_1: ${{ inputs.target-port-1}}
    TARGET_IP_2: ${{ inputs.target-ip-2}}
    TARGET_PORT_2: ${{ inputs.target-port-2}}
    TARGET_IP_3: ${{ inputs.target-ip-3}}
    TARGET_PORT_3: ${{ inputs.target-port-3}}

branding:
  icon: 'cloud'
  color: 'blue'